import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
    },
    roleText: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 16,
        marginBottom: 20,
    },
    optionButton: {
        backgroundColor: '#FF815E',
        padding: 10,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        width: 200,
        marginBottom: 20,
    },
    optionButtonText: {
        color: 'white',
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 16,
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 22,
    },
    modalView: {
        margin: 20,
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 35,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        height: 300,
        width: '80%',
    },
    modalText: {
        paddingHorizontal: 20,
        paddingVertical:40,
        marginBottom: 15,
        textAlign: 'left',
        height: '90%',
        width: '100%',
        fontFamily: 'Montserrat_500Medium',
        backgroundColor: '#F0F0F0',
        borderRadius: 20,
        textAlignVertical: 'top',
    },
    buttonClose: {
        borderRadius: 20,
        padding: 10,
        elevation: 2,
        backgroundColor: '#FF815E',
        width: 100,
        marginBottom: 10,
    },
    textStyle: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 10,
    },
    closeButtonText: {
        fontSize: 20,
        color: '#000',
    },
    deleteCenteredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 22,
    },
    deleteModalView: {
        width: '90%',
        margin: 20,
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 35,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    deleteButtonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 20,
    },
    deleteButtonClose: {
        backgroundColor: '#FF815E',
        padding: 10,
        width: '45%',
        borderRadius: 20,
    },
    deleteTextStyle: {
        color: 'white',
        fontFamily: 'Montserrat_600SemiBold',
        textAlign: 'center',
    },
    deleteModalText: {
        marginBottom: 18,
        textAlign: 'center',
        fontFamily: 'Montserrat_700Bold',
    },
});
