import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: '7%',
    },
    aboutContainer: {
        paddingVertical: 22,
        paddingHorizontal: 32,
        alignItems: 'center',
        justifyContent: 'center',
        alignContent: 'center',
        backgroundColor: 'white',
        width: '90%',
        height: 'auto',
        borderRadius: 12,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    text: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        marginVertical: 10,
        color: '#333',
    },
    upperText: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        marginTop: 10,
        color: '#333',
    },
    lowerText: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 10,
        color: '#333',
    },
    specialTitleText: {
        fontFamily: 'Montserrat_800ExtraBold',
        fontSize: 22,
        textAlign: 'center',
        marginVertical: 10,
        color: '#FF815E',
    },
    specialText: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 16,
        textAlign: 'center',
        marginVertical: 10,
        color: '#FF815E',
    },
});
