import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		backgroundColor: '#F0F0F0',
		alignItems: 'center',
	},
	goalsContainer: {
		width: '100%',
		height: '100%',
		paddingTop: '11%',
		paddingBottom: '7%',
		justifyContent: 'center',
		alignItems: 'center',
	},
	goalsListContainer: {
		width: '100%',
		paddingTop: 20,
		marginBottom: 20,
	},
	listItem: {
		height: '10%',
		padding: 5,
		backgroundColor: 'white',
		borderBottomWidth: 1,
		borderRadius: 12,
		borderColor: '#eee',
		width: '90%',
		alignSelf: 'center',
		marginBottom: '5%',
		justifyContent: 'center',
		alignItems: 'center',
	},
	infoSection: {
		justifyContent: 'center',
		alignContent: 'center',
		width: '60%',
		height: '100%',
		padding: 10,
	},
	buttonSection: {
		justifyContent: 'center',
		alignContent: 'center',
		alignItems: 'center',
		width: '40%',
		height: '100%',
	},
	currentGoalInfoSection: {
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignContent: 'center',
		alignItems: 'center',
	},
	currentGoalInfoTitle: {
		fontFamily: 'Montserrat_700Bold',
		fontSize: 18,
		fontWeight: 'bold',
	},
	currentGoalInfoText: {
		fontFamily: 'Montserrat_400Regular',
		fontSize: 18,
		justifyContent: 'center',
		alignItems: 'center',
	},
	text: {
		fontFamily: 'Montserrat_400Regular',
		fontSize: 18,
		justifyContent: 'center',
		alignItems: 'center',
	},
	goalSection: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignContent: 'center',
	},
	input: {
		fontFamily: 'Montserrat_400Regular',
		height: '82%',
		width: '50%',
		borderColor: 'gray',
		borderWidth: 1,
		borderRadius: 8,
		padding: 10,
		paddingHorizontal: 10,
		fontSize: 18,
		alignSelf: 'center',
	},
	button: {
		height: '85%',
		width: 'auto',
		backgroundColor: '#FF815E',
		paddingHorizontal: 20,
		paddingVertical: 10,
		borderRadius: 15,
		justifyContent: 'center',
		alignItems: 'center',
	},
	intialiseButton: {
		backgroundColor: '#FF815E',
		paddingHorizontal: 20,
		paddingVertical: 15,
		borderRadius: 15,
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 60,
		marginBottom: 20,
	},
	initialiseButtonText: {
		fontFamily: 'Montserrat_600SemiBold',
		textAlign: 'center',
		color: 'white',
		fontSize: 22,
		alignSelf: 'center',
	},
	initialiseInfoText: {
		fontFamily: 'Montserrat_500Medium',
		textAlign: 'center',
		fontSize: 14,
		alignSelf: 'center',
	},
	buttonText: {
		fontFamily: 'Montserrat_500Medium',
		textAlign: 'center',
		color: 'white',
		fontSize: 15,
		alignSelf: 'center',
	},
});
