import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    recentLogContainer: {
        alignItems: 'flex-start',
        justifyContent: 'center',
        padding: 5,
        backgroundColor: 'white',
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
        height: '95%',
        width: '94%',
        right: '1.5%',
    },
    recentLogTitleContainer: {
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        flexDirection: 'row',
        paddingLeft: 8,
        paddingBottom: 12,
        width: '100%',
        height: '40%',
    },
    innerRecentLogContainer: {
        justifyContent: 'center',
        alignItems: 'flex-start',
        backgroundColor: '#F5F5F5',
        borderRadius: 8,
        padding: 8,
        width: '92%',
        height: '50%',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
    },
    recentLogTitle: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 20,
        fontWeight: 'bold',
    },
    recentLogMealTypeText: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 17,
        fontWeight: 'bold',
        marginBottom: 7,
        marginLeft: 4,
    },
    logItemInfoText: {
        fontFamily: 'Montserrat_500Medium',
        fontSize: 17,
        fontWeight: '500',
        marginLeft: 4,
        marginBottom: 4,
    },
    recentLogCaloriesText: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 4,
    },
    logInfoText: {
        fontSize: 1,
        fontFamily: 'Montserrat_500Medium',
        fontWeight: '500',
        marginLeft: 4,
    },
    logInfoMeasurementText: {
        fontFamily: 'Montserrat_500Medium',
        fontSize: 16,
        fontWeight: '500',
        marginTop: 3.2,
        left: 2,
        marginLeft: 4,
    },
    noLogText: {
        textAlign: 'center',
        alignSelf: 'center',
        fontSize: 14,
        fontFamily: 'Montserrat_500Medium',
    },
});
