import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    progressBarComponentContainer: {
        justifyContent: 'center',
        marginTop: '0.8%',
        borderRadius: 15,
        width: '100%',
        height: '40%',
    },
    progressBarContainer: {
        flexDirection: 'row',
        marginTop: '1%',
        backgroundColor: '#F0F0F0',
        borderRadius: 32,
        overflow: 'hidden',
        width: '100%',
        height: 20,
    },
    filledProgressBar: {
        backgroundColor: '#FF815E',
        height: 20,
        borderRadius: 32,
    },
    progressBarItem: {
        marginBottom: 5,
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: 'white',
        borderRadius: 12,
        width: '100%',
        height: '25%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
    },
    labelContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    label: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 16,
        fontWeight: 'bold',
    },
    slideContainer: {
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        paddingHorizontal: 20,
    },
    firstSlideContainer: {
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        paddingHorizontal: 20,
        height: '100%',
        paddingBottom: 10,
    },
    firstLabel: {
        fontFamily: 'Montserrat_700Bold',
        top: 2,
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 7,
    },
    calorieProgressBarItem: {
        marginBottom: 5,
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: 'white',
        borderRadius: 12,
        width: '100%',
        height: '30%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
    },
    waterProgressBarItem: {
        marginTop: 10,
        marginBottom: 20,
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: 'white',
        borderRadius: 12,
        width: '100%',
        height: '30%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
    },
    slideTitle: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
        alignSelf: 'center',
    },
    remindersScrolView: {
        width: '100%',
        height: Platform.OS === 'android' ? '55%' : '58%',
        marginTop: 5.5,
        borderBottomRightRadius: 15,
        borderBottomLeftRadius: 15,
    },
    reminderItem: {
        marginBottom: '1.5%',
        justifyContent: 'center',
        alignItems: 'flex-start',
        paddingHorizontal: 20,
        paddingVertical: '2%',
        backgroundColor: 'white',
        borderRadius: 12,
        width: '100%',
        height: 52,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
    },
    reminderInfoSection: {
        marginTop: 6,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    reminderDescriptionText: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 16,
        fontWeight: 'bold',
    },
    reminderInfoTitle: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 12.5,
        fontWeight: '600',
    },
    reminderInfoText: {
        fontFamily: 'Montserrat_400Regular',
        fontSize: 12.5,
        fontWeight: '400',
        marginRight: 14,
    },
    seeAllRemindersButton: {
        width: '100%',
        height: 35,
        backgroundColor: '#F0F0F0',
        padding: 10,
        borderRadius: 15,
        alignItems: 'center',
        alignContent: 'center',
        justifyContent: 'center',
    },
    seeAllRemindersButtonText: {
        fontFamily: 'Montserrat_500Medium',
        fontSize: 12.5,
        fontWeight: '500',
        textTransform: 'uppercase',
    },
    emptyRemindersSection: {
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        marginVertical: 12,
        width: '90%',
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
    },
    emptyRemindersTitle: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
    },
    emptyRemindersText: {
        fontFamily: 'Montserrat_400Regular',
        fontSize: 14,
        fontWeight: '400',
        textAlign: 'center',
        marginBottom: 15,
    },
});
