name: Run Linting Tests

on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main,develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          fetch-depth: 0  

    - name: Install Modules
      run: npm ci 

    - name: Run ESLint
      run: npm run lint

